### PR TITLE
Configured backend, added apollo dependencies and schema.json file

### LINKED ISSUE #6: Implement graphql client together with showcase schema
# Part 1: 
Configure and document what backend is used for this application.
The suggested backend is located here:
https://github.com/aerogear/ionic-showcase/tree/master/server

# Part 2: 
Integrate and configure Apollo client for this repository:
https://www.apollographql.com/docs/android/

# Part 3: 
Query allTasks from the application and populate tasks list. 

# Note
 
The server has many advanced features including subscription. 
We do not need to integrate them now. 
Let's do a very basic query (allTasks) for the moment. We will focus on others in other tickets.

### PR DESCRIPTION
**Pull request by Lavanyagaur22**
**Description**

fix : #6  **Part 1** **Part 2** **Part 3**

**What is done**

-> First Commit

1. Added apollo-android and OkHttp3 dependency.
2. Used the backend provided in ionic-showcase application (using voyager server to get the local host and schema.json file)
3. Created the graphql directory and a getAlltasks.graphql file for query purposes.

-> Second Commit

4. Set-up Apollo client.
5. Populated the list with the result from the query of getting allTasks(). ( disabled fab functionality for adding new task for the moment)

**Screenshots of the work done**

Server-

[](https://postimg.cc/rdL979NG)

Android app-

[](https://postimg.cc/Snn5mV9w)

### CODE REVIEW

**Comment by Lavanyagaur22** [comment]
@wtrocki Done 👍 . Please have a look :)

**Comment by wtrocki** [comment]
@Lavanyagaur22  `Files changed 2,847` - it will be hard to get what was changed here. Can we configure gitignore and do not push changes that are not relevant to the issue? Alternatively, we can push those changes separately without PR.

**Comment by Lavanyagaur22** [comment]
@wtrocki  I added .gradle and .idea etc files in .gitignore still it's showing many files modified :/ Can you please help me out?

**Comment by wtrocki** [comment]
This is a git problem. One of the solutions: https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore

**Comment by Lavanyagaur22** [comment]
@wtrocki I did exactly the same and then I pushed it :(

**Comment by wtrocki** [comment]
Let's merge that and I will review this on the development  branch. It is simply that I have things to comment but PR is just too large to find this file.

**Comment by Lavanyagaur22** [comment]
@wtrocki Will keep this in mind from the next time and will make a pr to improve the project structure.

**Pull request merged**
